-- Create shares table
create table shares (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(post_id, user_id)
);

-- Add shares_count to posts
alter table posts add column shares_count int default 0;

-- Enable RLS for shares
alter table shares enable row level security;

create policy "Public shares are viewable by everyone" on shares for select using (true);
create policy "Authenticated users can insert shares" on shares for insert with check (auth.role() = 'authenticated');
create policy "Users can delete their own shares" on shares for delete using (auth.uid() = user_id);

-- Triggers for likes_count
create or replace function update_likes_count()
returns trigger as $$
begin
  if (TG_OP = 'INSERT') then
    update posts set likes_count = likes_count + 1 where id = new.post_id;
  elsif (TG_OP = 'DELETE') then
    update posts set likes_count = likes_count - 1 where id = old.post_id;
  end if;
  return null;
end;
$$ language plpgsql security definer;

create trigger on_like_change
after insert or delete on post_likes
for each row execute procedure update_likes_count();

-- Triggers for shares_count
create or replace function update_shares_count()
returns trigger as $$
begin
  if (TG_OP = 'INSERT') then
    update posts set shares_count = shares_count + 1 where id = new.post_id;
  elsif (TG_OP = 'DELETE') then
    update posts set shares_count = shares_count - 1 where id = old.post_id;
  end if;
  return null;
end;
$$ language plpgsql security definer;

create trigger on_share_change
after insert or delete on shares
for each row execute procedure update_shares_count();

-- Enable Realtime for post_likes and shares
alter publication supabase_realtime add table post_likes;
alter publication supabase_realtime add table shares;
