-- Enable necessary extensions
create extension if not exists "uuid-ossp";

-- 1. Enums
create type visibility_enum as enum ('public', 'followers', 'private');
create type notification_enum as enum ('like', 'comment', 'follow', 'message');
create type chat_type_enum as enum ('dm', 'group');

-- 2. Profiles (Extends auth.users)
create table profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  username text unique not null,
  full_name text,
  avatar_url text,
  bio text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- 3. Posts
create table posts (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  content text,
  visibility visibility_enum default 'public',
  likes_count int default 0,
  comments_count int default 0,
  deleted_at timestamptz,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table post_images (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  image_url text not null,
  created_at timestamptz default now()
);

create table post_likes (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(post_id, user_id)
);

-- 4. Comments
create table comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  likes_count int default 0,
  deleted_at timestamptz,
  created_at timestamptz default now()
);

create table comment_likes (
  id bigint generated by default as identity primary key,
  comment_id bigint references comments(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  unique(comment_id, user_id)
);

-- 5. Follows
create table follows (
  follower_id uuid references profiles(id) on delete cascade not null,
  following_id uuid references profiles(id) on delete cascade not null,
  created_at timestamptz default now(),
  primary key (follower_id, following_id)
);

-- 6. Notifications
create table notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null, -- Receiver
  actor_id uuid references profiles(id) on delete cascade not null, -- Actor
  type notification_enum not null,
  entity_id bigint not null, -- Polymorphic reference ID
  entity_type text not null, -- 'post', 'comment', 'chat'
  is_read boolean default false,
  created_at timestamptz default now()
);

-- 7. Chats
create table chats (
  id bigint generated by default as identity primary key,
  type chat_type_enum default 'dm',
  name text,
  image_url text,
  last_message_content text,
  last_message_at timestamptz default now(),
  created_at timestamptz default now()
);

create table chat_members (
  chat_id bigint references chats(id) on delete cascade not null,
  user_id uuid references profiles(id) on delete cascade not null,
  role text default 'member',
  joined_at timestamptz default now(),
  primary key (chat_id, user_id)
);

create table messages (
  id bigint generated by default as identity primary key,
  chat_id bigint references chats(id) on delete cascade not null,
  sender_id uuid references profiles(id) on delete cascade not null,
  content text not null,
  message_type text default 'text',
  is_read boolean default false,
  deleted_at timestamptz,
  created_at timestamptz default now()
);

-- 8. User Status (Realtime)
create table user_status (
  user_id uuid references profiles(id) on delete cascade primary key,
  online boolean default false,
  last_seen timestamptz default now()
);

-- 9. Triggers for updated_at
create or replace function update_updated_at_column()
returns trigger as $$
begin
  new.updated_at = now();
  return new;
end;
$$ language plpgsql;

create trigger update_profiles_updated_at
before update on profiles
for each row execute procedure update_updated_at_column();

create trigger update_posts_updated_at
before update on posts
for each row execute procedure update_updated_at_column();

-- 10. Trigger for Auto-Profile Creation
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, username, full_name, avatar_url)
  values (
    new.id,
    new.raw_user_meta_data->>'username',
    new.raw_user_meta_data->>'full_name',
    new.raw_user_meta_data->>'avatar_url'
  );
  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function every time a user is created
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

-- Enable Row Level Security (RLS)
alter table profiles enable row level security;
alter table posts enable row level security;
alter table post_images enable row level security;
alter table post_likes enable row level security;
alter table comments enable row level security;
alter table comment_likes enable row level security;
alter table follows enable row level security;
alter table notifications enable row level security;
alter table chats enable row level security;
alter table chat_members enable row level security;
alter table messages enable row level security;
alter table user_status enable row level security;

-- Basic Policies (Open for now, to be refined)
create policy "Public profiles are viewable by everyone" on profiles for select using (true);
create policy "Users can insert their own profile" on profiles for insert with check (auth.uid() = id);
create policy "Users can update own profile" on profiles for update using (auth.uid() = id);

create policy "Public posts are viewable by everyone" on posts for select using (visibility = 'public');
create policy "Authenticated users can create posts" on posts for insert with check (auth.role() = 'authenticated');
